'use strict';

// Typed failures for the CDP debug loop. Never surface bare "something went wrong".
const CODES = Object.freeze({
  CDP_ENDPOINT_UNAVAILABLE: 'CDP_ENDPOINT_UNAVAILABLE',
  TARGET_NOT_FOUND: 'TARGET_NOT_FOUND',
  TARGET_DETACHED: 'TARGET_DETACHED',
  TARGET_CONTEXT_UNAVAILABLE: 'TARGET_CONTEXT_UNAVAILABLE',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  RESPONSE_NOT_RECEIVED: 'RESPONSE_NOT_RECEIVED',
  RESPONSE_BODY_NOT_READY: 'RESPONSE_BODY_NOT_READY',
  RESPONSE_BODY_UNAVAILABLE: 'RESPONSE_BODY_UNAVAILABLE',
  CDP_BODY_FETCH_FAILED: 'CDP_BODY_FETCH_FAILED',
  REPLAY_FAILED: 'REPLAY_FAILED',
  REPLAY_TIMEOUT: 'REPLAY_TIMEOUT',
  HTTP_REPLAY_FAILED: 'HTTP_REPLAY_FAILED',
  REPLAY_BLOCKED_BY_BROWSER: 'REPLAY_BLOCKED_BY_BROWSER',
  INVALID_DRAFT: 'INVALID_DRAFT',
  INVALID_HEADER: 'INVALID_HEADER',
  INVALID_BODY: 'INVALID_BODY',
  INTERCEPT_TIMEOUT: 'INTERCEPT_TIMEOUT',
  INTERCEPT_CONTINUE_FAILED: 'INTERCEPT_CONTINUE_FAILED',
  INTERCEPT_ABORT_FAILED: 'INTERCEPT_ABORT_FAILED',
  INTERCEPT_NOT_FOUND: 'INTERCEPT_NOT_FOUND',
  INTERCEPT_ALREADY_RESOLVED: 'INTERCEPT_ALREADY_RESOLVED',
  INVALID_INTERCEPT_DRAFT: 'INVALID_INTERCEPT_DRAFT',
  // WU7 — Protocol Test Harness
  CONTROL_DISABLED_FOR_TARGET: 'CONTROL_DISABLED_FOR_TARGET',
  TEST_SESSION_UNAVAILABLE: 'TEST_SESSION_UNAVAILABLE',
  STALE_OR_MANUAL_SID: 'STALE_OR_MANUAL_SID',
  INVALID_TEST_REQUEST: 'INVALID_TEST_REQUEST',
  PROTOCOL_SEND_FAILED: 'PROTOCOL_SEND_FAILED',
  PROTOCOL_TEST_TIMEOUT: 'PROTOCOL_TEST_TIMEOUT',
  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',
  // WU8 — read-only observer (observational states only; never action errors)
  OBSERVER_SOCKET_UNAVAILABLE: 'OBSERVER_SOCKET_UNAVAILABLE',
  OBSERVER_PROTOCOL_CONTEXT_LOST: 'OBSERVER_PROTOCOL_CONTEXT_LOST',
  OBSERVER_ROUND_SUPERSEDED: 'OBSERVER_ROUND_SUPERSEDED',
  INVALID_OBSERVER_CONFIG: 'INVALID_OBSERVER_CONFIG',
  // WU10 — automated round runner
  AUTO_TEST_TARGET_NOT_ALLOWED: 'AUTO_TEST_TARGET_NOT_ALLOWED',
  AUTO_TEST_ALREADY_RUNNING: 'AUTO_TEST_ALREADY_RUNNING',
  AUTO_TEST_NOT_RUNNING: 'AUTO_TEST_NOT_RUNNING',
  INVALID_AUTO_TEST_CONFIG: 'INVALID_AUTO_TEST_CONFIG',
  ROUND_SID_UNAVAILABLE: 'ROUND_SID_UNAVAILABLE',
  BET_ACK_TIMEOUT: 'BET_ACK_TIMEOUT',
  CASHOUT_ACK_TIMEOUT: 'CASHOUT_ACK_TIMEOUT',
  ROUND_ENDED_BEFORE_THRESHOLD: 'ROUND_ENDED_BEFORE_THRESHOLD',
  PROTOCOL_SOCKET_NOT_FOUND: 'PROTOCOL_SOCKET_NOT_FOUND',
});

class CdpError extends Error {
  constructor(code, message, context) {
    super(message || code);
    this.name = 'CdpError';
    this.code = code;
    this.context = context || undefined;
  }
  toJSON() {
    return { code: this.code, message: this.message, context: this.context };
  }
}

module.exports = { CODES, CdpError };
