from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from websec_observer.domain.models import CapturedTransaction, Finding, TestProject, TestSession, WebSocketConnection, WebSocketFrame


class ProjectRepository(Protocol):
    async def add(self, project: TestProject) -> None: ...
    async def get(self, project_id: UUID) -> TestProject | None: ...
    async def list(self) -> Sequence[TestProject]: ...


class SessionRepository(Protocol):
    async def add(self, session: TestSession) -> None: ...
    async def get(self, session_id: UUID) -> TestSession | None: ...
    async def update(self, session: TestSession) -> None: ...


class FindingRepository(Protocol):
    async def add_many(self, findings: Sequence[Finding]) -> None: ...
    async def list_for_session(self, session_id: UUID) -> Sequence[Finding]: ...


class TransactionRepository(Protocol):
    async def add_many(self, transactions: Sequence[CapturedTransaction]) -> None: ...
    async def list_for_session(self, session_id: UUID) -> Sequence[CapturedTransaction]: ...


class WebSocketRepository(Protocol):
    async def add_connection(self, connection: WebSocketConnection) -> None: ...
    async def close_connection(self, connection_id: UUID, closed_at: object) -> None: ...
    async def add_frames(self, frames: Sequence[WebSocketFrame]) -> None: ...
    async def list_for_session(self, session_id: UUID) -> Sequence[WebSocketFrame]: ...


class UnitOfWork(Protocol):
    projects: ProjectRepository
    sessions: SessionRepository
    findings: FindingRepository
    transactions: TransactionRepository
    websockets: WebSocketRepository

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
