const events = [];
const selected = new Set();
const rows = document.querySelector('#requests');
const workspace = document.querySelector('#workspace');
const projectCard = document.querySelector('.project-switch');
const productStyle = document.createElement('style'); productStyle.textContent = '.project-field{display:grid;gap:4px;color:var(--muted);font-size:10px}.project-field input{width:100%;height:28px;border:1px solid var(--line);border-radius:6px;padding:0 7px;background:var(--surface);color:var(--text);font-size:10px}.response-card{margin-top:25px;border:1px solid var(--line);border-radius:9px;background:var(--surface);padding:14px}.response-card small{display:block;color:var(--muted);font-size:9px;letter-spacing:.1em}.response-card strong{display:block;color:var(--accent);font-size:22px;margin:8px 0}.response-card pre{max-height:220px;overflow:auto;white-space:pre-wrap;color:var(--muted);font-size:11px}.session-row{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;border-bottom:1px solid var(--line);background:var(--surface)}.session-row b,.session-row span{display:block}.session-row span{color:var(--muted);font-size:11px;margin-top:4px}.session-row button{border:1px solid var(--line);background:var(--surface);color:var(--accent);border-radius:6px;padding:8px 11px}#selection-bar{display:none;position:absolute;bottom:18px;left:18px;right:18px;z-index:4;gap:10px;align-items:center;padding:10px 12px;background:var(--header);color:#fff;border-radius:8px;box-shadow:0 5px 20px #0003}#selection-bar button{border:1px solid #52717a;background:transparent;color:#fff;border-radius:5px;padding:6px 9px;font-size:10px}#selection-bar button:first-of-type{margin-left:auto;background:var(--accent);border-color:var(--accent)}'; document.head.appendChild(productStyle);
projectCard.insertAdjacentHTML('beforeend', '<label class="project-field">Webapp URL<input id="target-url" value="https://staging.example.com"></label><label class="project-field">Allowed domains<input id="scope" placeholder="app.local, api.local, *.cdn.com"></label>');
try { document.querySelector('#target-url').value = localStorage.getItem('observatory-target-url') || 'https://staging.example.com'; document.querySelector('#scope').value = localStorage.getItem('observatory-scope') || ''; } catch {}
const copy = { vi: { status: 'Sẵn sàng', open: 'Mở Chromium', title: 'Requests', subtitle: 'Chọn request để xem và thay giá trị.', captured: 'Requests đã bắt', select: 'Chọn tất cả', empty: 'Chưa có request', emptyHint: 'Mở Chromium và thao tác trên webapp.', workspace: 'Request workspace', workspaceHint: 'Chọn request để sửa value và replay.', search: 'Tìm host, path hoặc method' }, en: { status: 'Ready', open: 'Open Chromium', title: 'Requests', subtitle: 'Select requests to review and replace values.', captured: 'Captured requests', select: 'Select all', empty: 'No requests yet', emptyHint: 'Open Chromium and use your webapp.', workspace: 'Request workspace', workspaceHint: 'Choose a request to edit values and replay.', search: 'Search host, path or method' } };
function applyLanguage(language) { const text = copy[language] || copy.en; document.querySelector('#status').textContent = text.status; document.querySelector('#open').textContent = text.open; document.querySelector('#view-title').textContent = text.title; document.querySelector('#view-subtitle').textContent = text.subtitle; document.querySelector('.list-head b').textContent = text.captured; document.querySelector('#select-all').textContent = text.select; document.querySelector('#search').placeholder = text.search; document.documentElement.lang = language; try { localStorage.setItem('observatory-language', language); } catch {} }
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function urlInfo(raw) { try { const url = new URL(raw); return { url, path: url.pathname + (url.search || '') }; } catch { return { url: null, path: raw }; } }
function render() {
  const query = document.querySelector('#search').value.toLowerCase();
  const type = document.querySelector('#type').value;
  const list = events.filter(event => event.kind === 'request').filter(event => type === 'all' || event.resourceType === type).filter(event => !query || (event.url + event.method).toLowerCase().includes(query));
  document.querySelector('#count').textContent = list.length;
  if (!list.length) { rows.innerHTML = '<div class="empty"><strong>No requests yet</strong><span>Open Chromium and use your webapp.</span></div>'; return; }
  rows.innerHTML = list.slice().reverse().map(event => {
    const info = urlInfo(event.url); const response = events.find(item => item.kind === 'response' && item.id === event.id);
    return '<div class="row ' + (selected.has(event.id) ? 'selected' : '') + '" data-id="' + esc(event.id) + '"><input type="checkbox" ' + (selected.has(event.id) ? 'checked' : '') + '><span class="method">' + esc(event.method) + '</span><span>' + esc(event.resourceType) + '</span><span><b class="host">' + esc(info.url?.host || '') + '</b><span class="path">' + esc(info.path) + '</span></span><span class="status">' + esc(response?.status || '…') + '</span><span>' + esc(event.scope === 'allow_metadata_only' ? 'metadata' : 'in scope') + '</span></div>';
  }).join('');
  rows.querySelectorAll('.row').forEach(row => row.onclick = event => { if (event.target.tagName === 'INPUT') { event.stopPropagation(); row.querySelector('input').checked ? selected.add(row.dataset.id) : selected.delete(row.dataset.id); row.classList.toggle('selected', selected.has(row.dataset.id)); return; } openWorkspace(row.dataset.id); });
  renderSelectionBar();
}
function renderSelectionBar() { let bar = document.querySelector('#selection-bar'); if (!bar) { bar = document.createElement('div'); bar.id = 'selection-bar'; document.querySelector('.request-list').appendChild(bar); } bar.innerHTML = selected.size ? '<b>' + selected.size + ' selected</b><button id="bulk-replay">Replay sequence</button><button id="clear-selected">Clear selection</button>' : ''; bar.style.display = selected.size ? 'flex' : 'none'; if (selected.size) { bar.querySelector('#clear-selected').onclick = () => { selected.clear(); render(); }; bar.querySelector('#bulk-replay').onclick = replaySequence; } }
async function replaySequence() { const chosen = [...selected].map(id => events.find(event => event.kind === 'request' && event.id === id)).filter(Boolean); const results = []; for (const request of chosen) { const result = await window.desktopCapture?.replay(request.id, {}); results.push({ id: request.id, status: result?.status || 0, ok: result?.ok !== false }); } workspace.innerHTML = '<div class="replace"><h2>Replay sequence</h2><p class="subtitle">Completed ' + results.length + ' request(s) in selection order.</p><div class="response-card"><pre>' + esc(JSON.stringify(results, null, 2)) + '</pre></div></div>'; }
function openWorkspace(id) {
  const request = events.find(event => event.kind === 'request' && event.id === id); if (!request) return;
  const info = urlInfo(request.url); if (!info.url) return;
  const params = [...info.url.searchParams.entries()]; let bodyFields = []; try { const body = JSON.parse(request.bodyPreview || ''); if (body && typeof body === 'object' && !Array.isArray(body)) bodyFields = Object.entries(body); } catch {}
  const originalResponse = events.find(event => event.kind === 'response' && event.id === request.id); workspace.innerHTML = '<div class="replace"><div class="subtitle">' + esc(request.method) + ' · ' + esc(info.url.host) + '</div><h2>Replace request values</h2><p class="subtitle">Only values can be changed. Request identity stays fixed.</p><h3>Query parameters</h3>' + (params.length ? params.map(pair => '<div class="param"><label>' + esc(pair[0]) + '</label><input data-kind="query" data-key="' + esc(pair[0]) + '" value="' + esc(pair[1]) + '"></div>').join('') : '<div class="subtitle">No query parameters</div>') + (bodyFields.length ? '<h3>Body parameters</h3>' + bodyFields.map(pair => '<div class="param"><label>' + esc(pair[0]) + '</label><input data-kind="body" data-key="' + esc(pair[0]) + '" value="' + esc(typeof pair[1] === 'string' ? pair[1] : JSON.stringify(pair[1])) + '"></div>').join('') : '') + '<button class="replay" id="replay">Replay request</button><div class="response-card"><small>LAST RESPONSE</small><strong>' + esc(originalResponse?.status || 'Pending') + '</strong><pre id="result">' + esc(originalResponse ? JSON.stringify(originalResponse, null, 2) : '') + '</pre></div></div>';
  document.querySelector('#replay').onclick = async () => { const replacement = new URL(request.url); workspace.querySelectorAll('[data-kind="query"]').forEach(input => replacement.searchParams.set(input.dataset.key, input.value)); const overrides = { url: replacement.toString() }; const bodyInputs = workspace.querySelectorAll('[data-kind="body"]'); if (bodyInputs.length) { const body = {}; bodyInputs.forEach(input => { try { body[input.dataset.key] = JSON.parse(input.value); } catch { body[input.dataset.key] = input.value; } }); overrides.body = JSON.stringify(body); } const result = await (window.desktopCapture?.browserReplay ? window.desktopCapture.browserReplay(request.id, { method: request.method, url: overrides.url, body: overrides.body }) : window.desktopCapture?.replay(request.id, overrides)); document.querySelector('#result').textContent = JSON.stringify(result, null, 2); };
}
function renderReplayHistory() { const items = events.filter(event => event.kind === 'replay').slice().reverse(); rows.innerHTML = items.length ? items.map(event => '<div class="row"><span></span><span class="method">REPLAY</span><span>' + esc(event.status || 0) + '</span><span><b class="host">' + esc(event.url) + '</b><span class="path">' + esc((event.overrides || []).join(', ') || 'captured values') + '</span></span><span class="status">' + esc(event.status || 0) + '</span><span>' + esc(event.timestamp || '') + '</span></div>').join('') : '<div class="empty"><strong>No replay history</strong><span>Replay results will appear here.</span></div>'; }
function renderFindings() { rows.innerHTML = '<div class="empty"><strong>Findings are not available for this session yet</strong><span>Run passive analysis after importing the session into the Python service.</span></div>'; }
async function renderSessions() { const sessions = await window.desktopCapture?.listSessions?.() || []; rows.innerHTML = sessions.length ? sessions.slice().reverse().map(session => '<div class="session-row"><div><b>' + esc(session.startedAt ? new Date(session.startedAt).toLocaleString() : session.id.slice(0, 8)) + '</b><span>' + esc(session.requestCount + ' requests') + '</span></div><button data-session="' + esc(session.id) + '">Load</button><button data-export="' + esc(session.id) + '">Journal</button><button data-report="' + esc(session.id) + '">HTML</button><button data-har="' + esc(session.id) + '">HAR</button></div>').join('') : '<div class="empty"><strong>No saved sessions</strong><span>Sessions appear after capture starts.</span></div>'; rows.querySelectorAll('[data-session]').forEach(button => button.onclick = async () => { const loaded = await window.desktopCapture.readSession(button.dataset.session); events.length = 0; events.push(...loaded); selected.clear(); document.querySelector('#view-title').textContent = 'Requests'; render(); }); rows.querySelectorAll('[data-export]').forEach(button => button.onclick = async () => { await window.desktopCapture.exportSession(button.dataset.export); }); rows.querySelectorAll('[data-report]').forEach(button => button.onclick = async () => { await window.desktopCapture.exportSessionReport(button.dataset.report, 'html'); }); rows.querySelectorAll('[data-har]').forEach(button => button.onclick = async () => { await window.desktopCapture.exportSessionReport(button.dataset.har, 'har'); }); }
document.querySelectorAll('.nav').forEach(item => item.onclick = () => { document.querySelectorAll('.nav').forEach(nav => nav.classList.toggle('active', nav === item)); const view = item.dataset.view; if (view === 'replays') { document.querySelector('#view-title').textContent = 'Replay history'; document.querySelector('#view-subtitle').textContent = 'Review previous replay attempts.'; renderReplayHistory(); } else if (view === 'sessions') { document.querySelector('#view-title').textContent = 'Saved sessions'; document.querySelector('#view-subtitle').textContent = 'Load a previous capture session.'; renderSessions(); } else if (view === 'findings') { document.querySelector('#view-title').textContent = 'Findings'; document.querySelector('#view-subtitle').textContent = 'Passive analysis results.'; renderFindings(); } else { document.querySelector('#view-title').textContent = 'Requests'; document.querySelector('#view-subtitle').textContent = 'Select requests to review and replace values.'; render(); } });
document.querySelector('#open').onclick = () => { const target = document.querySelector('#target-url').value.trim(); if (!target) return; const hosts = (document.querySelector('#scope').value || new URL(target).hostname).split(',').map(value => value.trim()).filter(Boolean); window.desktopCapture?.setScope(hosts); window.desktopCapture?.openBrowser(target); try { localStorage.setItem('observatory-target-url', target); localStorage.setItem('observatory-scope', hosts.join(', ')); } catch {} document.querySelector('#status').textContent = 'Capturing'; document.querySelector('#scope-label').textContent = hosts.join(', '); };
document.querySelector('#search').oninput = render;
document.querySelector('#type').onchange = render;
document.querySelector('#select-all').onclick = () => { events.filter(event => event.kind === 'request').forEach(event => selected.add(event.id)); render(); };
document.querySelector('#theme').onclick = () => { const next = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; document.documentElement.dataset.theme = next; try { localStorage.setItem('observatory-theme', next); } catch {} };
const language = document.querySelector('#lang'); const savedLanguage = (() => { try { return localStorage.getItem('observatory-language') || 'vi'; } catch { return 'vi'; } })(); language.value = savedLanguage; applyLanguage(savedLanguage); language.onchange = () => applyLanguage(language.value);
try { document.documentElement.dataset.theme = localStorage.getItem('observatory-theme') || 'light'; } catch {}
window.desktopCapture?.onEvent(event => { events.push(event); render(); });
render();
