let current;
const detail = document.querySelector('#detail');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(payload) {
  current = payload; const request = payload.request; const response = payload.response; const url = new URL(request.url); document.querySelector('#title').textContent = request.method + ' ' + url.pathname;
  detail.innerHTML = '<div class="scope-row"><b>URL</b><span class="mono">' + esc(request.url) + '</span></div><div class="scope-row"><b>Host</b><span>' + esc(url.host) + '</span></div><div class="scope-row"><b>Status</b><span>' + (response ? response.status : 'pending') + '</span></div><div class="scope-row"><b>Duration</b><span>' + (response ? response.duration + ' ms' : 'pending') + '</span></div><div class="scope-row"><b>Scope</b><span>' + esc(request.scope) + '</span></div><h3>Request headers</h3><pre class="mono">' + esc(JSON.stringify(request.headers || {}, null, 2)) + '</pre><h3>Request body preview</h3><pre class="mono">' + esc(request.bodyPreview || '(empty or unavailable)') + '</pre><h3>Response</h3><pre class="mono">' + esc(JSON.stringify(response || {}, null, 2)) + '</pre><div class="detail-actions"><button id="copy">Copy redacted cURL</button><button id="replay">Replay request</button></div><pre id="result" class="mono"></pre>';
  document.querySelector('#copy').onclick = async () => { await navigator.clipboard.writeText('curl -X ' + request.method + ' "' + request.url + '" -H "Authorization: [REDACTED]"'); document.querySelector('#copy').textContent = 'Copied'; };
  document.querySelector('#replay').onclick = async () => { if (!window.confirm('Replay this request to the same in-scope host?')) return; const replacementUrl = window.prompt('Optional replacement URL (same host only):', request.url); if (replacementUrl === null) return; const body = ['GET','HEAD'].includes(request.method) ? undefined : window.prompt('Optional replacement body:', ''); const output = await window.desktopCapture.replay(request.id, { url: replacementUrl, ...(body === null ? {} : { body }) }); document.querySelector('#result').textContent = JSON.stringify(output, null, 2); };
}
window.desktopCapture?.onDetailData(render);
