let current;
const detail = document.querySelector('#detail');
const style = document.createElement('style'); style.textContent = '.edit-field{width:70%;border:1px solid #d7e0e3;border-radius:4px;padding:8px;font:11px ui-monospace}.edit-area{width:100%;min-height:100px;border:1px solid #d7e0e3;border-radius:5px;padding:10px;font:11px/1.5 ui-monospace;resize:vertical}.detail-window h3 small{font-weight:400;color:#829097}'; document.head.appendChild(style);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(payload) {
  current = payload; const request = payload.request; const response = payload.response; const url = new URL(request.url); document.querySelector('#title').textContent = request.method + ' ' + url.pathname;
  const originalUrl = request.url;
  const originalHeaders = JSON.stringify(request.headers || {}, null, 2);
  const originalBody = request.bodyPreview || '';
  detail.innerHTML = '<div class="scope-row"><b>URL</b><input id="edit-url" class="edit-field" value="' + esc(request.url) + '"></div><div class="scope-row"><b>Host</b><span>' + esc(url.host) + '</span></div><div class="scope-row"><b>Status</b><span>' + (response ? response.status : 'pending') + '</span></div><div class="scope-row"><b>Duration</b><span>' + (response ? response.duration + ' ms' : 'pending') + '</span></div><div class="scope-row"><b>Scope</b><span>' + esc(request.scope) + '</span></div><h3>Request headers <small>(editable JSON)</small></h3><textarea id="edit-headers" class="edit-area">' + esc(originalHeaders) + '</textarea><h3>Request body <small>(editable)</small></h3><textarea id="edit-body" class="edit-area">' + esc(originalBody) + '</textarea><h3>Response</h3><pre class="mono">' + esc(JSON.stringify(response || {}, null, 2)) + '</pre><div class="detail-actions"><button id="copy">Copy redacted cURL</button><button id="replay">Replay edited request</button></div><pre id="result" class="mono"></pre>';
  document.querySelector('#copy').onclick = async () => { await navigator.clipboard.writeText('curl -X ' + request.method + ' "' + request.url + '" -H "Authorization: [REDACTED]"'); document.querySelector('#copy').textContent = 'Copied'; };
  document.querySelector('#replay').onclick = async () => { if (!window.confirm('Replay the edited request to the same in-scope host?')) return; const urlValue = document.querySelector('#edit-url').value; const headerText = document.querySelector('#edit-headers').value; const bodyValue = document.querySelector('#edit-body').value; let headers = {}; try { headers = JSON.parse(headerText || '{}'); } catch { document.querySelector('#result').textContent = 'Headers must be valid JSON'; return; } const overrides = {}; if (urlValue !== originalUrl) overrides.url = urlValue; if (headerText !== originalHeaders) overrides.headers = headers; if (bodyValue !== originalBody) overrides.body = bodyValue; const output = await window.desktopCapture.replay(request.id, overrides); document.querySelector('#result').textContent = JSON.stringify(output, null, 2); };
}
window.desktopCapture?.onDetailData(render);
