const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('desktopCapture', {
  setScope: hosts => ipcRenderer.invoke('scope-set', hosts),
  setPaused: paused => ipcRenderer.invoke('capture-toggle', paused),
  replayCreateDraft: (capturedRequestId, options) => ipcRenderer.invoke('replay-create-draft', capturedRequestId, options),
  replayUpdateDraft: (draftId, patch) => ipcRenderer.invoke('replay-update-draft', draftId, patch),
  replayExecute: draftId => ipcRenderer.invoke('replay-execute', draftId),
  replayHistory: capturedRequestId => ipcRenderer.invoke('replay-history', capturedRequestId),
  wsSend: (capturedId, payload) => ipcRenderer.invoke('ws-send', capturedId, payload),
  timelineBuild: capturedRequestId => ipcRenderer.invoke('timeline-build', capturedRequestId),
  cookiesSave: targetId => ipcRenderer.invoke('cookies-save', targetId),
  cookiesRestore: (targetId, reload) => ipcRenderer.invoke('cookies-restore', targetId, reload),
  interceptEnable: (rule, targetId) => ipcRenderer.invoke('intercept-enable', rule, targetId),
  interceptDisable: targetId => ipcRenderer.invoke('intercept-disable', targetId),
  interceptList: () => ipcRenderer.invoke('intercept-list'),
  interceptUpdateDraft: (id, patch) => ipcRenderer.invoke('intercept-update-draft', id, patch),
  interceptContinue: id => ipcRenderer.invoke('intercept-continue', id),
  interceptContinueModified: (id, patch) => ipcRenderer.invoke('intercept-continue-modified', id, patch),
  interceptAbort: id => ipcRenderer.invoke('intercept-abort', id),
  onInterceptChanged: callback => ipcRenderer.on('intercept-changed', (_event, paused) => callback(paused)),
  openBrowser: url => ipcRenderer.invoke('open-browser', url),
  listSessions: () => ipcRenderer.invoke('list-sessions'),
  readSession: sessionId => ipcRenderer.invoke('read-session', sessionId),
  exportSession: sessionId => ipcRenderer.invoke('export-session', sessionId),
  exportSessionReport: (sessionId, format) => ipcRenderer.invoke('export-session-report', sessionId, format),
  analyzeSession: sessionId => ipcRenderer.invoke('analyze-session', sessionId),
  getResponseBody: capturedId => ipcRenderer.invoke('get-response-body', capturedId),
  getRequestDetail: capturedId => ipcRenderer.invoke('get-request-detail', capturedId),
  connect: endpoint => ipcRenderer.invoke('cdp-connect', endpoint),
  listTargets: () => ipcRenderer.invoke('list-targets'),
  selectTarget: id => ipcRenderer.invoke('select-target', id),
  adbListWebviews: () => ipcRenderer.invoke('adb-list-webviews'),
  adbForwardWebview: (socket, localPort) => ipcRenderer.invoke('adb-forward-webview', socket, localPort),
  // WU7 — Protocol Test Harness
  protocolEnvironment: targetId => ipcRenderer.invoke('protocol-environment', targetId),
  protocolAllowlist: () => ipcRenderer.invoke('protocol-allowlist'),
  protocolRoundState: () => ipcRenderer.invoke('protocol-round-state'),
  protocolTemplate: (command, overrides) => ipcRenderer.invoke('protocol-template', command, overrides),
  protocolCheckSid: sid => ipcRenderer.invoke('protocol-check-sid', sid),
  protocolExecute: opts => ipcRenderer.invoke('protocol-execute', opts),
  protocolExecutions: () => ipcRenderer.invoke('protocol-executions'),
  onAviatorRound: callback => ipcRenderer.on('aviator-round', (_event, round) => callback(round)),
  protocolContext: () => ipcRenderer.invoke('protocol-context'),
  onProtocolContext: callback => ipcRenderer.on('protocol-context', (_event, ctx) => callback(ctx)),
  onAviatorActionTrace: callback => ipcRenderer.on('aviator-actiontrace', (_event, trace) => callback(trace)),
  onProtocolExecution: callback => ipcRenderer.on('protocol-execution', (_event, ex) => callback(ex)),
  // WU8 — read-only Round/ODD observer
  observerSnapshot: () => ipcRenderer.invoke('observer-snapshot'),
  observerConfig: patch => ipcRenderer.invoke('observer-config', patch),
  onObserverUpdate: callback => ipcRenderer.on('observer-update', (_event, snap) => callback(snap)),
  // WU10 — offline automated round test runner
  autotestEnvironment: targetId => ipcRenderer.invoke('autotest-environment', targetId),
  autotestStart: config => ipcRenderer.invoke('autotest-start', config),
  autotestStop: () => ipcRenderer.invoke('autotest-stop'),
  autotestSnapshot: () => ipcRenderer.invoke('autotest-snapshot'),
  onAutotestUpdate: callback => ipcRenderer.on('autotest-update', (_event, snap) => callback(snap)),
  // WU10.2 — bet amount server validation
  bvalidateEnvironment: targetId => ipcRenderer.invoke('bvalidate-environment', targetId),
  bvalidateStart: config => ipcRenderer.invoke('bvalidate-start', config),
  bvalidateStop: () => ipcRenderer.invoke('bvalidate-stop'),
  bvalidateSnapshot: () => ipcRenderer.invoke('bvalidate-snapshot'),
  onBvalidateUpdate: callback => ipcRenderer.on('bvalidate-update', (_event, snap) => callback(snap)),
  onTargetsChanged: callback => ipcRenderer.on('targets-changed', (_event, targets) => callback(targets)),
  onCdpError: callback => ipcRenderer.on('cdp-error', (_event, error) => callback(error)),
  onEvent: callback => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('capture-event', listener);
    return () => ipcRenderer.removeListener('capture-event', listener);
  }
});
