const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('desktopCapture', {
  setScope: hosts => ipcRenderer.invoke('scope-set', hosts),
  setPaused: paused => ipcRenderer.invoke('capture-toggle', paused),
  replayCreateDraft: (capturedRequestId, options) => ipcRenderer.invoke('replay-create-draft', capturedRequestId, options),
  replayUpdateDraft: (draftId, patch) => ipcRenderer.invoke('replay-update-draft', draftId, patch),
  replayExecute: draftId => ipcRenderer.invoke('replay-execute', draftId),
  replayHistory: capturedRequestId => ipcRenderer.invoke('replay-history', capturedRequestId),
  wsSend: (capturedId, payload) => ipcRenderer.invoke('ws-send', capturedId, payload),
  timelineBuild: capturedRequestId => ipcRenderer.invoke('timeline-build', capturedRequestId),
  cookiesSave: targetId => ipcRenderer.invoke('cookies-save', targetId),
  cookiesRestore: (targetId, reload) => ipcRenderer.invoke('cookies-restore', targetId, reload),
  interceptEnable: (rule, targetId) => ipcRenderer.invoke('intercept-enable', rule, targetId),
  interceptDisable: targetId => ipcRenderer.invoke('intercept-disable', targetId),
  interceptList: () => ipcRenderer.invoke('intercept-list'),
  interceptUpdateDraft: (id, patch) => ipcRenderer.invoke('intercept-update-draft', id, patch),
  interceptContinue: id => ipcRenderer.invoke('intercept-continue', id),
  interceptContinueModified: (id, patch) => ipcRenderer.invoke('intercept-continue-modified', id, patch),
  interceptAbort: id => ipcRenderer.invoke('intercept-abort', id),
  onInterceptChanged: callback => ipcRenderer.on('intercept-changed', (_event, paused) => callback(paused)),
  openBrowser: url => ipcRenderer.invoke('open-browser', url),
  copyText: text => ipcRenderer.invoke('copy-text', text),
  licenseStatus: () => ipcRenderer.invoke('license-status'),
  activateLicense: license => ipcRenderer.invoke('license-activate', license),
  onLicenseChanged: callback => ipcRenderer.on('license-changed', (_event, status) => callback(status)),
  instanceInfo: () => ipcRenderer.invoke('instance-info'),
  listSessions: () => ipcRenderer.invoke('list-sessions'),
  readSession: sessionId => ipcRenderer.invoke('read-session', sessionId),
  exportSession: sessionId => ipcRenderer.invoke('export-session', sessionId),
  exportSessionReport: (sessionId, format) => ipcRenderer.invoke('export-session-report', sessionId, format),
  analyzeSession: sessionId => ipcRenderer.invoke('analyze-session', sessionId),
  getResponseBody: capturedId => ipcRenderer.invoke('get-response-body', capturedId),
  getRequestDetail: capturedId => ipcRenderer.invoke('get-request-detail', capturedId),
  connect: endpoint => ipcRenderer.invoke('cdp-connect', endpoint),
  listTargets: () => ipcRenderer.invoke('list-targets'),
  selectTarget: id => ipcRenderer.invoke('select-target', id),
  adbListWebviews: () => ipcRenderer.invoke('adb-list-webviews'),
  adbForwardWebview: (socket, localPort) => ipcRenderer.invoke('adb-forward-webview', socket, localPort),
  // WU-C.1 — persistent browser management (registry-backed).
  listBrowsers: () => ipcRenderer.invoke('browser-list'),
  browserCapacity: () => ipcRenderer.invoke('browser-capacity'),
  createBrowser: input => ipcRenderer.invoke('browser-create', input),
  openBrowserById: browserId => ipcRenderer.invoke('browser-open', browserId),
  updateBrowser: (browserId, patch) => ipcRenderer.invoke('browser-update', browserId, patch),
  deleteBrowser: browserId => ipcRenderer.invoke('browser-delete', browserId),
  onBrowsersChanged: callback => ipcRenderer.on('browsers-changed', (_event, payload) => callback(payload)),
  // WU-A/WU-B — browser run selection (view state) + explicit run binding.
  listRuns: () => ipcRenderer.invoke('list-runs'),
  selectRun: runId => ipcRenderer.invoke('select-run', runId),
  closeRun: runId => ipcRenderer.invoke('close-run', runId),
  onRunsChanged: callback => ipcRenderer.on('runs-changed', (_event, runs) => callback(runs)),
  // WU7 — Protocol Test Harness. Every execution IPC carries an EXPLICIT runId so a
  // send/ack binds to that browser run, never to whichever run the UI is viewing.
  protocolEnvironment: (runId, targetId) => ipcRenderer.invoke('protocol-environment', runId, targetId),
  protocolAllowlist: runId => ipcRenderer.invoke('protocol-allowlist', runId),
  protocolRoundState: runId => ipcRenderer.invoke('protocol-round-state', runId),
  protocolTemplate: (runId, command, overrides) => ipcRenderer.invoke('protocol-template', runId, command, overrides),
  protocolCheckSid: (runId, sid) => ipcRenderer.invoke('protocol-check-sid', runId, sid),
  protocolExecute: (runId, opts) => ipcRenderer.invoke('protocol-execute', runId, opts),
  protocolExecutions: runId => ipcRenderer.invoke('protocol-executions', runId),
  onAviatorRound: callback => ipcRenderer.on('aviator-round', (_event, round) => callback(round)),
  protocolContext: runId => ipcRenderer.invoke('protocol-context', runId),
  onProtocolContext: callback => ipcRenderer.on('protocol-context', (_event, ctx) => callback(ctx)),
  onAviatorActionTrace: callback => ipcRenderer.on('aviator-actiontrace', (_event, trace) => callback(trace)),
  onProtocolExecution: callback => ipcRenderer.on('protocol-execution', (_event, ex) => callback(ex)),
  // WU8 — read-only Round/ODD observer
  observerSnapshot: runId => ipcRenderer.invoke('observer-snapshot', runId),
  observerConfig: (runId, patch) => ipcRenderer.invoke('observer-config', runId, patch),
  onObserverUpdate: callback => ipcRenderer.on('observer-update', (_event, snap) => callback(snap)),
  // WU10 — automated round test runner (explicit run binding)
  autotestEnvironment: (runId, targetId) => ipcRenderer.invoke('autotest-environment', runId, targetId),
  autotestStart: (runId, config) => ipcRenderer.invoke('autotest-start', runId, config),
  autotestStop: runId => ipcRenderer.invoke('autotest-stop', runId),
  autotestSnapshot: runId => ipcRenderer.invoke('autotest-snapshot', runId),
  onAutotestUpdate: callback => ipcRenderer.on('autotest-update', (_event, snap) => callback(snap)),
  // WU10.2 — bet amount server validation (explicit run binding)
  bvalidateEnvironment: (runId, targetId) => ipcRenderer.invoke('bvalidate-environment', runId, targetId),
  bvalidateStart: (runId, config) => ipcRenderer.invoke('bvalidate-start', runId, config),
  bvalidateStop: runId => ipcRenderer.invoke('bvalidate-stop', runId),
  bvalidateSnapshot: runId => ipcRenderer.invoke('bvalidate-snapshot', runId),
  onBvalidateUpdate: callback => ipcRenderer.on('bvalidate-update', (_event, snap) => callback(snap)),
  onTargetsChanged: callback => ipcRenderer.on('targets-changed', (_event, targets) => callback(targets)),
  onCdpError: callback => ipcRenderer.on('cdp-error', (_event, error) => callback(error)),
  onEvent: callback => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('capture-event', listener);
    return () => ipcRenderer.removeListener('capture-event', listener);
  }
});
